apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          imagePullPolicy: Always
          image: ${GOOGLE_REGISTRY_URL}/service1:${CIRCLE_WORKFLOW_ID}
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: service1-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: service1
  type: LoadBalancer
  loadBalancerIP: ""
